In [1]:
import torch
import numpy as np

### add / sub / mul / div

In [2]:
a = torch.rand(3,4)
b = torch.rand(4)

In [3]:
a

tensor([[0.4313, 0.3821, 0.9614, 0.4631],
        [0.7687, 0.8547, 0.9691, 0.4726],
        [0.3387, 0.9575, 0.3755, 0.3116]])

In [4]:
b

tensor([0.5289, 0.7934, 0.0463, 0.1310])

In [5]:
a+b

tensor([[0.9602, 1.1755, 1.0077, 0.5940],
        [1.2977, 1.6481, 1.0155, 0.6036],
        [0.8677, 1.7509, 0.4218, 0.4426]])

In [6]:
a.add(b)

tensor([[0.9602, 1.1755, 1.0077, 0.5940],
        [1.2977, 1.6481, 1.0155, 0.6036],
        [0.8677, 1.7509, 0.4218, 0.4426]])

In [7]:
torch.add(a,b)

tensor([[0.9602, 1.1755, 1.0077, 0.5940],
        [1.2977, 1.6481, 1.0155, 0.6036],
        [0.8677, 1.7509, 0.4218, 0.4426]])

In [8]:
torch.all(torch.eq(a-b, torch.sub(a,b)))

tensor(True)

In [9]:
torch.all(torch.eq(a*b, torch.mul(a,b)))

tensor(True)

In [10]:
torch.all(torch.eq(a/b, torch.div(a,b)))

tensor(True)

### matmul

- torch.mm
    - only for 2d
- torch.matmul
- @ (@ 等价于 matmul)

tensor([[0.4313, 0.3821, 0.9614, 0.4631],
        [0.7687, 0.8547, 0.9691, 0.4726],
        [0.3387, 0.9575, 0.3755, 0.3116]])

In [17]:
a = torch.tensor([[3.,3.],[3.,3.]])
a

tensor([[3., 3.],
        [3., 3.]])

In [23]:
b = torch.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [25]:
torch.mm(a, b)

tensor([[6., 6.],
        [6., 6.]])

In [26]:
torch.matmul(a, b)

tensor([[6., 6.],
        [6., 6.]])

In [27]:
a @ b

tensor([[6., 6.],
        [6., 6.]])

For example

In [28]:
# 线性层相加
# 降维
a = torch.rand(4, 784)

In [29]:
x = torch.rand(4, 784)

In [30]:
w = torch.rand(512, 784)

In [31]:
(x @ w.t()).shape     # .t只适合2d矩阵

torch.Size([4, 512])

\>2d tensor matmul

In [33]:
a = torch.rand(4, 3, 28, 64)
b = torch.rand(4, 3, 64, 32)

In [34]:
# 错误
torch.mm(a, b).shape

RuntimeError: self must be a matrix

In [35]:
torch.matmul(a, b).shape

torch.Size([4, 3, 28, 32])

In [36]:
b = torch.rand(4, 1, 64, 32)

a = [4, 3, 28, 64]  
b = [4, 1, 64, 32]  
b先进行广播变为[4, 3, 64, 32]再进行矩阵乘法

In [37]:
torch.matmul(a, b).shape

torch.Size([4, 3, 28, 32])

In [38]:
b = torch.rand(4, 64, 32)
torch.matmul(a, b).shape

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

### Power

In [45]:
torch.set_default_tensor_type(torch.FloatTensor)

In [53]:
a = torch.full([2,2], 3.)

In [54]:
a

tensor([[3., 3.],
        [3., 3.]])

In [55]:
a.pow(2)

tensor([[9., 9.],
        [9., 9.]])

In [56]:
a ** 2

tensor([[9., 9.],
        [9., 9.]])

In [57]:
aa = a**2

In [58]:
aa.sqrt()

tensor([[3., 3.],
        [3., 3.]])

In [59]:
aa.rsqrt()

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333]])

In [61]:
torch.sqrt(aa)

tensor([[3., 3.],
        [3., 3.]])

In [62]:
aa ** (0.5)

tensor([[3., 3.],
        [3., 3.]])

### Exp log

In [63]:
a = torch.exp(torch.ones(2, 2))

In [64]:
a

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [65]:
torch.log(a)

tensor([[1., 1.],
        [1., 1.]])

In [66]:
torch.log2(a)

tensor([[1.4427, 1.4427],
        [1.4427, 1.4427]])

### Approximation

- .floor() .ceil()
- .round()
- .trunc() .frac()

In [67]:
a = torch.tensor(3.14)

In [68]:
a

tensor(3.1400)

In [69]:
a.floor(), a.ceil(), a.trunc(), a.frac()

(tensor(3.), tensor(4.), tensor(3.), tensor(0.1400))

In [70]:
a = torch.tensor(3.4999)

In [71]:
a.round()

tensor(3.)

In [72]:
a = torch.tensor(3.5)

In [74]:
a.round()

tensor(4.)

### clamp（限幅）

- gradient clipping
- (min)
- (min, max)

In [77]:
grad = torch.rand(2, 3) * 15

In [78]:
grad.max()

tensor(10.5926)

In [79]:
grad.median()

tensor(2.7863)

In [80]:
grad.clamp(10)

tensor([[10.0000, 10.0000, 10.5926],
        [10.0000, 10.0000, 10.0000]])

In [81]:
grad

tensor([[ 1.6833,  7.2684, 10.5926],
        [ 2.7863,  9.2941,  2.7013]])

In [82]:
grad.clamp(0, 10)

tensor([[ 1.6833,  7.2684, 10.0000],
        [ 2.7863,  9.2941,  2.7013]])