In [1]:
import torch
import numpy as np

In [13]:
torch.__version__

'1.7.0'

In [2]:
torch.tensor(1)

tensor(1)

In [3]:
torch.Tensor(1)

tensor([0.])

In [12]:
torch.tensor([1])

tensor([1])

In [4]:
torch.tensor([1.1, 2.2])

tensor([1.1000, 2.2000])

In [5]:
torch.Tensor([1.1, 2.2])

tensor([1.1000, 2.2000])

In [6]:
torch.FloatTensor(1)

tensor([-1.8891e+26])

In [7]:
torch.FloatTensor(2)

tensor([nan, 0.])

In [8]:
torch.FloatTensor(2)

tensor([-1.0842e-19,  2.0250e+00])

In [9]:
data = np.ones(2)

In [10]:
data

array([1., 1.])

In [11]:
torch.from_numpy(data)

tensor([1., 1.], dtype=torch.float64)

In [14]:
a = torch.ones(2)

In [15]:
a.shape

torch.Size([2])

In [16]:
a

tensor([1., 1.])

In [17]:
a.dim()

1

In [18]:
a.size()

torch.Size([2])

In [19]:
a.type()

'torch.FloatTensor'

In [20]:
type(a)

torch.Tensor

In [22]:
len(a.size())

1

In [23]:
isinstance(a, torch.FloatTensor)

True

Dim 2

In [24]:
a = torch.randn(2, 3)

In [25]:
a

tensor([[-0.7032, -0.1355, -0.1631],
        [ 0.0415, -0.6659, -1.9330]])

In [26]:
a.shape

torch.Size([2, 3])

In [27]:
a.size()

torch.Size([2, 3])

In [28]:
a.size(0)

2

In [29]:
a.size(1)

3

In [30]:
a.shape[1]

3

In [31]:
a.shape[0]

2

Dim 3

In [32]:
a = torch.rand(1,2,3)

In [33]:
a

tensor([[[0.7811, 0.0476, 0.6882],
         [0.5455, 0.7305, 0.7988]]])

In [34]:
a.shape

torch.Size([1, 2, 3])

In [35]:
a[0]

tensor([[0.7811, 0.0476, 0.6882],
        [0.5455, 0.7305, 0.7988]])

In [36]:
list(a.shape)

[1, 2, 3]

In [38]:
a.dim()

3

Dim 4

In [39]:
a = torch.rand(2, 3, 28, 28)

In [40]:
a

tensor([[[[0.6225, 0.9077, 0.1200,  ..., 0.5768, 0.3314, 0.8236],
          [0.3795, 0.1376, 0.2567,  ..., 0.4222, 0.2220, 0.8278],
          [0.8695, 0.8187, 0.0055,  ..., 0.8259, 0.7629, 0.1818],
          ...,
          [0.2856, 0.1566, 0.6744,  ..., 0.1662, 0.4110, 0.7823],
          [0.2214, 0.9634, 0.4655,  ..., 0.3972, 0.6993, 0.2699],
          [0.8643, 0.1242, 0.4106,  ..., 0.6477, 0.4887, 0.0312]],

         [[0.7268, 0.6182, 0.5186,  ..., 0.5567, 0.3282, 0.8998],
          [0.3977, 0.7274, 0.5983,  ..., 0.8236, 0.9431, 0.2473],
          [0.6217, 0.5852, 0.2780,  ..., 0.1833, 0.1635, 0.9674],
          ...,
          [0.7008, 0.4737, 0.3808,  ..., 0.6020, 0.9053, 0.7144],
          [0.3172, 0.5551, 0.2729,  ..., 0.1560, 0.9394, 0.4214],
          [0.4168, 0.2021, 0.2350,  ..., 0.4076, 0.7278, 0.5885]],

         [[0.3801, 0.2057, 0.1274,  ..., 0.8220, 0.1191, 0.0649],
          [0.7477, 0.5394, 0.4398,  ..., 0.3156, 0.1867, 0.1333],
          [0.1742, 0.5316, 0.5100,  ..., 0

In [41]:
a.shape

torch.Size([2, 3, 28, 28])

Mixed

In [42]:
a.shape

torch.Size([2, 3, 28, 28])

In [43]:
a.numel()

4704

In [44]:
a.dim()

4

In [45]:
a = torch.tensor(1)

In [47]:
a.dim()

0