In [1]:
import torch
import numpy as np

### norm（范数）

In [9]:
a = torch.full([8],1.)

In [10]:
a

tensor([1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
b = a.view(2, 4)

In [12]:
c = a.view(2,2,2)

In [13]:
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
c

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [15]:
display(a.norm(1), b.norm(1),c.norm(1))

tensor(8.)

tensor(8.)

tensor(8.)

In [16]:
display(a.norm(2), b.norm(2),c.norm(2))

tensor(2.8284)

tensor(2.8284)

tensor(2.8284)

In [21]:
 b.norm(1, dim = 1)

tensor([4., 4.])

In [22]:
b.norm(2, dim = 1)

tensor([2., 2.])

In [28]:
c.norm(1, dim = 0)

tensor([[2., 2.],
        [2., 2.]])

In [26]:
c.norm(2, dim = 0)

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

### mean,sum,min,max,prod

In [30]:
a = torch.arange(8).view(2, 4).float()

In [31]:
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [32]:
display(a.min(), a.max(), a.mean(), a.prod())  # prod累乘

tensor(0.)

tensor(7.)

tensor(3.5000)

tensor(0.)

In [33]:
a.sum()

tensor(28.)

In [34]:
a.argmax(),a.argmin()   # 将维度打平为1，再求位置

(tensor(7), tensor(0))

In [35]:
a = a.view(1, 2 ,4)

In [36]:
a

tensor([[[0., 1., 2., 3.],
         [4., 5., 6., 7.]]])

In [37]:
a.argmax()

tensor(7)

In [38]:
a.argmin()

tensor(0)

In [40]:
a = torch.rand(2, 3, 4)

In [41]:
a

tensor([[[0.2635, 0.9018, 0.0386, 0.6583],
         [0.0246, 0.0886, 0.2330, 0.4859],
         [0.4234, 0.2305, 0.3673, 0.9567]],

        [[0.5895, 0.1352, 0.3370, 0.6981],
         [0.8443, 0.7619, 0.7267, 0.1005],
         [0.2287, 0.5845, 0.7332, 0.9233]]])

In [42]:
a.argmax()

tensor(11)

In [43]:
a = torch.randn(4, 10)

In [44]:
a

tensor([[-0.1065,  0.0204, -1.2815, -1.5421, -0.0864,  0.3025,  1.0177,  0.5609,
          1.1736,  1.0888],
        [-0.5943,  0.3358,  0.2059,  0.2164, -0.2503,  0.2818,  2.0965,  0.3376,
         -0.0106,  0.4209],
        [-0.7711,  0.9429, -0.0567, -1.3778, -1.3599, -2.0151, -1.4744, -1.1300,
         -0.9886,  1.1849],
        [-1.5083, -0.4905,  0.4842,  1.0931,  1.4971, -0.3563,  0.1371,  2.0128,
         -0.6092,  1.3387]])

In [45]:
a[0]

tensor([-0.1065,  0.0204, -1.2815, -1.5421, -0.0864,  0.3025,  1.0177,  0.5609,
         1.1736,  1.0888])

In [46]:
a.argmax()

tensor(16)

In [47]:
a.argmax(dim = 1)

tensor([8, 6, 9, 7])

In [48]:
a.argmax(dim = 0)

tensor([0, 2, 3, 3, 3, 0, 1, 3, 0, 3])

### dim, keepdim

In [50]:
a

tensor([[-0.1065,  0.0204, -1.2815, -1.5421, -0.0864,  0.3025,  1.0177,  0.5609,
          1.1736,  1.0888],
        [-0.5943,  0.3358,  0.2059,  0.2164, -0.2503,  0.2818,  2.0965,  0.3376,
         -0.0106,  0.4209],
        [-0.7711,  0.9429, -0.0567, -1.3778, -1.3599, -2.0151, -1.4744, -1.1300,
         -0.9886,  1.1849],
        [-1.5083, -0.4905,  0.4842,  1.0931,  1.4971, -0.3563,  0.1371,  2.0128,
         -0.6092,  1.3387]])

In [51]:
a.max(dim = 1)

torch.return_types.max(
values=tensor([1.1736, 2.0965, 1.1849, 2.0128]),
indices=tensor([8, 6, 9, 7]))

In [52]:
a.argmax(dim = 1)

tensor([8, 6, 9, 7])

In [53]:
a.max(dim = 1, keepdim = True)

torch.return_types.max(
values=tensor([[1.1736],
        [2.0965],
        [1.1849],
        [2.0128]]),
indices=tensor([[8],
        [6],
        [9],
        [7]]))

In [54]:
a.argmax(dim = 1, keepdim=True)

tensor([[8],
        [6],
        [9],
        [7]])

In [55]:
a.argmax(dim = 0, keepdim=True)

tensor([[0, 2, 3, 3, 3, 0, 1, 3, 0, 3]])

In [56]:
a.max(dim = 0, keepdim = True)

torch.return_types.max(
values=tensor([[-0.1065,  0.9429,  0.4842,  1.0931,  1.4971,  0.3025,  2.0965,  2.0128,
          1.1736,  1.3387]]),
indices=tensor([[0, 2, 3, 3, 3, 0, 1, 3, 0, 3]]))

### top-k or k-th

In [61]:
a.topk(3, dim = 1)

torch.return_types.topk(
values=tensor([[ 1.1736,  1.0888,  1.0177],
        [ 2.0965,  0.4209,  0.3376],
        [ 1.1849,  0.9429, -0.0567],
        [ 2.0128,  1.4971,  1.3387]]),
indices=tensor([[8, 9, 6],
        [6, 9, 7],
        [9, 1, 2],
        [7, 4, 9]]))

In [62]:
a.topk(3, dim = 1, largest=False)   # 找最小的K个

torch.return_types.topk(
values=tensor([[-1.5421, -1.2815, -0.1065],
        [-0.5943, -0.2503, -0.0106],
        [-2.0151, -1.4744, -1.3778],
        [-1.5083, -0.6092, -0.4905]]),
indices=tensor([[3, 2, 0],
        [0, 4, 8],
        [5, 6, 3],
        [0, 8, 1]]))

In [63]:
a.kthvalue(8, dim = 1)    # 查询第k小的元素

torch.return_types.kthvalue(
values=tensor([ 1.0177,  0.3376, -0.0567,  1.3387]),
indices=tensor([6, 7, 2, 9]))

In [64]:
a.kthvalue(3)

torch.return_types.kthvalue(
values=tensor([-0.1065, -0.0106, -1.3778, -0.4905]),
indices=tensor([0, 8, 3, 1]))

In [65]:
a.kthvalue(3, dim = 1)

torch.return_types.kthvalue(
values=tensor([-0.1065, -0.0106, -1.3778, -0.4905]),
indices=tensor([0, 8, 3, 1]))

In [66]:
a.kthvalue(3, dim = 0)

torch.return_types.kthvalue(
values=tensor([-0.5943,  0.3358,  0.2059,  0.2164, -0.0864,  0.2818,  1.0177,  0.5609,
        -0.0106,  1.1849]),
indices=tensor([1, 1, 1, 1, 0, 1, 0, 0, 1, 2]))

### compare

- \>,>=,<,<=,!=,==
- torch.eq(a, b)
    - torch.equal(a, b)

In [70]:
a > 0

tensor([[False,  True, False, False, False,  True,  True,  True,  True,  True],
        [False,  True,  True,  True, False,  True,  True,  True, False,  True],
        [False,  True, False, False, False, False, False, False, False,  True],
        [False, False,  True,  True,  True, False,  True,  True, False,  True]])

In [71]:
torch.gt(a, 0)

tensor([[False,  True, False, False, False,  True,  True,  True,  True,  True],
        [False,  True,  True,  True, False,  True,  True,  True, False,  True],
        [False,  True, False, False, False, False, False, False, False,  True],
        [False, False,  True,  True,  True, False,  True,  True, False,  True]])

In [72]:
a != 0

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [74]:
a=torch.ones(2, 3)

In [79]:
b = torch.randn(2, 3)

In [80]:
torch.eq(a, b)

tensor([[False, False, False],
        [False, False, False]])

In [81]:
torch.eq(a, a)

tensor([[True, True, True],
        [True, True, True]])

In [82]:
torch.equal(a,a)

True