In [1]:
import numpy as np
import torch

### where

example

In [4]:
cond = torch.rand(2,2)

In [5]:
cond

tensor([[0.5418, 0.2717],
        [0.9077, 0.6897]])

In [8]:
a = torch.zeros(2,2)
a

tensor([[0., 0.],
        [0., 0.]])

In [10]:
b = torch.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [11]:
torch.where(cond > 0.5, a, b)

tensor([[0., 1.],
        [0., 0.]])

### gather（查表）

#### retrieve global label

- argmax(pred) to get relative labeling
- On some condition, our label is distinct from relative labeling

In [12]:
prob = torch.randn(4, 10)

In [14]:
idx = prob.topk(dim = 1, k = 3)
idx

torch.return_types.topk(
values=tensor([[2.7366, 0.2287, 0.1332],
        [2.4573, 1.4894, 0.9173],
        [2.5545, 1.4233, 0.9839],
        [2.7151, 1.5210, 1.3558]]),
indices=tensor([[9, 7, 1],
        [0, 6, 1],
        [6, 5, 8],
        [3, 2, 7]]))

In [15]:
idx = idx[1]
idx

tensor([[9, 7, 1],
        [0, 6, 1],
        [6, 5, 8],
        [3, 2, 7]])

In [16]:
label = torch.arange(10) + 100
label

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [19]:
label.expand(4, 10)

tensor([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [18]:
torch.gather(label.expand(4, 10), dim = 1, index = idx)

tensor([[109, 107, 101],
        [100, 106, 101],
        [106, 105, 108],
        [103, 102, 107]])