In [1]:
import torch
import numpy as np

import from numpy

In [2]:
a = np.array([2,3,3])

In [3]:
torch.from_numpy(a)

tensor([2, 3, 3], dtype=torch.int32)

In [4]:
a = np.ones([2, 3])

In [5]:
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

import from tensor

In [6]:
torch.tensor([2., 3.2])

tensor([2.0000, 3.2000])

In [7]:
torch.FloatTensor([2., 3.2])

tensor([2.0000, 3.2000])

In [14]:
torch.tensor([[2., 3.2],[1., 22.3]])

tensor([[ 2.0000,  3.2000],
        [ 1.0000, 22.3000]])

In [13]:
torch.Tensor([[2., 3.2],[1., 22.3]])

tensor([[ 2.0000,  3.2000],
        [ 1.0000, 22.3000]])

uninitialized

In [70]:
torch.empty(1,3)

tensor([[0., 0., 0.]])

In [68]:
torch.tensor([1,2,3]).shape

torch.Size([3])

In [71]:
torch.Tensor(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [74]:
torch.IntTensor(2, 3)

tensor([[ 909455922,  959590707,  842019892],
        [ 825634913,  875717473, 1647456568]], dtype=torch.int32)

In [73]:
torch.FloatTensor(2, 3)

tensor([[6.5564e-10, 1.0244e-11, 4.3916e-05],
        [1.3075e+22, 6.7003e-10, 1.6147e-07]])

set default type

In [76]:
torch.tensor([1.2, 3]).type()

'torch.FloatTensor'

In [79]:
torch.Tensor(1,2).type()

'torch.FloatTensor'

In [82]:
torch.set_default_tensor_type(torch.DoubleTensor)

In [83]:
torch.tensor([1.2, 3]).type()

'torch.DoubleTensor'

In [84]:
torch.Tensor(1,2).type()

'torch.DoubleTensor'

rand/rand_like, randint

In [86]:
torch.set_default_tensor_type(torch.FloatTensor)

In [87]:
torch.rand(3,3)

tensor([[0.4751, 0.6693, 0.0550],
        [0.6213, 0.7354, 0.4916],
        [0.6891, 0.7604, 0.3701]])

In [89]:
a = torch.rand(3,3)

In [90]:
torch.rand_like(a)

tensor([[0.7457, 0.8518, 0.7766],
        [0.7953, 0.9224, 0.8598],
        [0.8332, 0.7807, 0.1314]])

In [96]:
torch.randint(1, 10,(3,3))

tensor([[8, 6, 9],
        [5, 5, 4],
        [6, 4, 3]])

randn

In [97]:
torch.randn(3,3)

tensor([[ 1.3928, -0.8169,  0.5617],
        [ 0.7499,  0.6365, -0.5169],
        [ 1.3277, -0.4293,  0.0907]])

In [101]:
torch.normal(mean=torch.full([10], 0,dtype = torch.double), std=torch.arange(1, 0, -0.1, dtype = torch.double))

tensor([ 0.2035,  0.3649,  1.1144, -0.1587,  0.0242, -0.8016, -0.1129,  0.0845,
         0.0499, -0.0805], dtype=torch.float64)

full

In [102]:
torch.full([2, 3], 7)

tensor([[7, 7, 7],
        [7, 7, 7]])

In [103]:
torch.full([], 7)

tensor(7)

In [104]:
torch.full([1], 7)

tensor([7])

arange/ range

In [105]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [107]:
torch.range(0, 10)

D:\Anaconda\envs\Pytorch\lib\site-packages\ipykernel_launcher.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  """Entry point for launching an IPython kernel.


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

linspace / logspace

In [108]:
torch.linspace(0, 10, steps = 4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [110]:
torch.linspace(0, 10, steps = 10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [111]:
torch.linspace(0, 10 ,steps = 11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [112]:
torch.logspace(0, -1, steps = 10)

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

In [113]:
torch.logspace(0, 1, steps = 10)

tensor([ 1.0000,  1.2915,  1.6681,  2.1544,  2.7826,  3.5938,  4.6416,  5.9948,
         7.7426, 10.0000])

ones / zeros / eye

In [114]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [115]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [116]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [118]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [119]:
a = torch.zeros(3, 3)

In [122]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

randperm

In [123]:
torch.randperm(10)

tensor([5, 6, 1, 4, 9, 7, 8, 2, 0, 3])

In [125]:
# 做shuffle
a = torch.rand(2, 3)

In [127]:
b = torch.rand(2, 2)

In [150]:
a

tensor([[0.0086, 0.6921, 0.3265],
        [0.8276, 0.1554, 0.6844]])

In [151]:
b

tensor([[0.8524, 0.7535],
        [0.0200, 0.9359]])

In [128]:
idx = torch.randperm(2)

In [149]:
idx

tensor([1, 0])

In [152]:
a[idx]

tensor([[0.8276, 0.1554, 0.6844],
        [0.0086, 0.6921, 0.3265]])

In [153]:
b[idx]

tensor([[0.0200, 0.9359],
        [0.8524, 0.7535]])